#!/usr/bin/env bash
# Sync spec/openapi.yaml from the canonical Comfy API v2 spec.
#
# The canonical spec lives in a private, internal repo. This repo is
# public, so we never vendor it verbatim — we vendor a FILTERED copy (see
# spec/README.md and scripts/filter_openapi.py for what "filtered" means
# and why).
#
# Usage:
#   scripts/sync-spec.sh <path-or-url-to-canonical-openapi.yaml> [source-ref]
#
# Examples:
#   scripts/sync-spec.sh <local-checkout>/path/to/openapi.yaml <sha>
#   scripts/sync-spec.sh https://<raw-host>/<sha>/path/to/openapi.yaml <sha>
#
# This is the same filter step the proposed cloud-side workflow
# (docs/sync-workflow.md) runs in CI to open the sync PR automatically —
# this script is what you run locally to reproduce it, or what that
# workflow shells out to after checking out this repo. There is exactly
# one place the filtering logic lives (scripts/filter_openapi.py), so the
# manual and automated paths can never drift apart.
set -euo pipefail

if [[ $# -lt 1 || $# -gt 2 ]]; then
  echo "usage: $0 <path-or-url-to-canonical-openapi.yaml> [source-ref]" >&2
  exit 2
fi

SOURCE="$1"
SOURCE_REF="${2:-unknown}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SPEC_DIR="$REPO_ROOT/spec"
OUT_SPEC="$SPEC_DIR/openapi.yaml"
OUT_VERSION="$SPEC_DIR/VERSION"

WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

if [[ "$SOURCE" =~ ^https?:// ]]; then
  echo "sync-spec: fetching $SOURCE" >&2
  curl -fsSL "$SOURCE" -o "$WORKDIR/canonical-openapi.yaml"
  SOURCE_INPUT="$WORKDIR/canonical-openapi.yaml"
else
  if [[ ! -f "$SOURCE" ]]; then
    echo "sync-spec: no such file: $SOURCE" >&2
    exit 1
  fi
  SOURCE_INPUT="$SOURCE"
fi

echo "sync-spec: filtering $SOURCE_INPUT -> $OUT_SPEC" >&2
python3 "$REPO_ROOT/scripts/filter_openapi.py" "$SOURCE_INPUT" "$OUT_SPEC"

SPEC_VERSION="$(python3 -c "
import yaml, sys
with open('$OUT_SPEC') as f:
    spec = yaml.safe_load(f)
print(spec.get('info', {}).get('version', 'unknown'))
")"

cat > "$OUT_VERSION" <<EOF
# Generated by scripts/sync-spec.sh — do not hand-edit.
# Pin for the spec vendored at spec/openapi.yaml.
source_ref=$SOURCE_REF
spec_info_version=$SPEC_VERSION
synced_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

echo "sync-spec: wrote $OUT_VERSION" >&2
echo "sync-spec: done. Review the diff, then regenerate models:" >&2
echo "  python3 scripts/generate_models.py" >&2
